"""initial system schema

Revision ID: 45c4e9d14015
Revises: 
Create Date: 2026-08-24 10:26:16.320957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c4e9d14015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('total_exp_earned', sa.Integer(), nullable=False),
    sa.Column('stat_points', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('perception', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=True)

    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.Enum('DAILY', 'NORMAL', name='questtype', native_enum=False, length=16), nullable=False),
    sa.Column('difficulty', sa.Enum('E', 'D', 'C', 'B', 'A', 'S', name='questdifficulty', native_enum=False, length=2), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=False),
    sa.Column('stat_reward', sa.Enum('STRENGTH', 'AGILITY', 'VITALITY', 'INTELLIGENCE', 'PERCEPTION', name='statname', native_enum=False, length=16), nullable=True),
    sa.Column('stat_reward_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_player_id'), ['player_id'], unique=False)

    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('QUEST_CREATED', 'QUEST_PROGRESS', 'QUEST_COMPLETED', 'QUEST_FAILED', 'LEVEL_UP', 'STATS_ALLOCATED', 'PENALTY_APPLIED', 'DAILY_RESET', name='eventtype', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_player_id'), ['player_id'], unique=False)

    op.create_table('quest_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('quest_date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='queststatus', native_enum=False, length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'quest_date', name='uq_quest_instance_per_day')
    )
    with op.batch_alter_table('quest_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_instances_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_instances_quest_date'), ['quest_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_instances_quest_id'), ['quest_id'], unique=False)

    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('quest_instance_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('exp_lost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_instance_id'], ['quest_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_player_id'))

    op.drop_table('penalties')
    with op.batch_alter_table('quest_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_instances_quest_id'))
        batch_op.drop_index(batch_op.f('ix_quest_instances_quest_date'))
        batch_op.drop_index(batch_op.f('ix_quest_instances_player_id'))

    op.drop_table('quest_instances')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_player_id'))
        batch_op.drop_index(batch_op.f('ix_system_events_created_at'))

    op.drop_table('system_events')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_player_id'))

    op.drop_table('quests')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_user_id'))

    op.drop_table('players')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
