"""flexible quest schedules

Replaces the binary daily/normal quest_type with an authored schedule, and
generalizes a quest instance from a single date to a period.

Hand-written rather than left as autogenerated: Alembic's version dropped
quest_type and quest_date and added the new columns empty, which would have
discarded every existing quest and its history. This migrates the data across.

  quest_type DAILY  -> schedule DAILY, one-day periods
  quest_type NORMAL -> schedule ONCE,  open-ended period (never lapses)

Revision ID: afff1562526e
Revises: 45c4e9d14015
Create Date: 2026-08-24 10:48:14.882094
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "afff1562526e"
down_revision: Union[str, Sequence[str], None] = "45c4e9d14015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Non-native enums persist the member NAME, so comparisons here are uppercase.
SCHEDULE_ENUM = sa.Enum(
    "ONCE",
    "DAILY",
    "WEEKDAYS",
    "INTERVAL",
    "WEEKLY",
    name="schedulekind",
    native_enum=False,
    length=16,
)


def upgrade() -> None:
    # 1. Add the new quest columns as nullable so existing rows survive.
    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("schedule", SCHEDULE_ENUM, nullable=True))
        batch_op.add_column(sa.Column("schedule_days", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("schedule_interval_days", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("schedule_anchor", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("week_start", sa.Integer(), nullable=True))

    # 2. Carry the old quest_type across.
    op.execute(
        """
        UPDATE quests
           SET schedule = CASE quest_type WHEN 'DAILY' THEN 'DAILY' ELSE 'ONCE' END,
               week_start = 0
        """
    )

    # 3. Add the period columns, still nullable.
    with op.batch_alter_table("quest_instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("period_start", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("period_end", sa.Date(), nullable=True))

    # 4. Every old instance covered exactly one day. A recurring quest's period
    #    closes that same day; a one-time quest's stays open indefinitely.
    op.execute("UPDATE quest_instances SET period_start = quest_date")
    op.execute(
        """
        UPDATE quest_instances
           SET period_end = quest_date
         WHERE quest_id IN (SELECT id FROM quests WHERE schedule <> 'ONCE')
        """
    )

    # 5. Now that every row is populated, tighten the constraints and drop the
    #    superseded columns.
    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.alter_column("schedule", existing_type=SCHEDULE_ENUM, nullable=False)
        batch_op.alter_column("week_start", existing_type=sa.Integer(), nullable=False)
        batch_op.drop_column("quest_type")

    with op.batch_alter_table("quest_instances", schema=None) as batch_op:
        batch_op.alter_column("period_start", existing_type=sa.Date(), nullable=False)
        batch_op.drop_index(batch_op.f("ix_quest_instances_quest_date"))
        batch_op.drop_constraint(
            batch_op.f("uq_quest_instance_per_day"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_quest_instances_period_start"), ["period_start"]
        )
        batch_op.create_index(
            batch_op.f("ix_quest_instances_period_end"), ["period_end"]
        )
        batch_op.create_unique_constraint(
            "uq_quest_instance_per_period", ["quest_id", "period_start"]
        )
        batch_op.drop_column("quest_date")


def downgrade() -> None:
    """Return to the daily/normal model.

    Lossy by nature: weekdays, interval, and weekly schedules have no
    representation in the old model and come back as NORMAL one-time quests.
    A multi-day period collapses to its start date.
    """
    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quest_type", sa.VARCHAR(length=16), nullable=True))

    op.execute(
        """
        UPDATE quests
           SET quest_type = CASE schedule WHEN 'DAILY' THEN 'DAILY' ELSE 'NORMAL' END
        """
    )

    with op.batch_alter_table("quest_instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quest_date", sa.DATE(), nullable=True))

    op.execute("UPDATE quest_instances SET quest_date = period_start")

    with op.batch_alter_table("quest_instances", schema=None) as batch_op:
        batch_op.alter_column("quest_date", existing_type=sa.DATE(), nullable=False)
        batch_op.drop_constraint("uq_quest_instance_per_period", type_="unique")
        batch_op.drop_index(batch_op.f("ix_quest_instances_period_start"))
        batch_op.drop_index(batch_op.f("ix_quest_instances_period_end"))
        batch_op.create_unique_constraint(
            batch_op.f("uq_quest_instance_per_day"), ["quest_id", "quest_date"]
        )
        batch_op.create_index(
            batch_op.f("ix_quest_instances_quest_date"), ["quest_date"]
        )
        batch_op.drop_column("period_end")
        batch_op.drop_column("period_start")

    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.alter_column(
            "quest_type", existing_type=sa.VARCHAR(length=16), nullable=False
        )
        batch_op.drop_column("week_start")
        batch_op.drop_column("schedule_anchor")
        batch_op.drop_column("schedule_interval_days")
        batch_op.drop_column("schedule_days")
        batch_op.drop_column("schedule")
